### ISSUE TITLE
The training of the Inverse dynamics model

### ISSUE THREAD

**Issue by penghao-wu** [metadriverse/ACO#2]
Hi, how many training samples are used for the training of the Inverse dynamics model (only samples data or all the sweeps data), and do you scale and center crop the nuscenes image to 320*180 for training? 
Also, when calculating the optical flow for training, is the time interval between current and next image 1s? 
Thanks in advance.

**Comment by zqh0253** [comment]
Hi, 
1. All the train data in NuScenes is used.
2. I scale the image to 320*180 without center crop.
3. Yes, the interval is 1s.

But note that, the inverse prediction performance is not perfect under this setup (especially throttle prediction, so ACO only uses steering).

**Comment by penghao-wu** [comment]
Thank you for your reply.

**Comment by penghao-wu** [comment]
Hi, currently I get the steer angle from can_bus.vehicle_monitor for nuscenes data. Is this correct? Also, how do you normalize the steer angle to 0-1?

**Comment by penghao-wu** [comment]
I also notice that you give different weight to samples, how to calculate these weights based on the steer?

**Comment by zqh0253** [comment]
1. Yes, steering is from vehicle monitor.
2. I use statistics (mean, std) from the entire data set for normalization.
3. During training, uniform sampling strategy is used. Different weights are used for visualization and evaluating only.
