### ISSUE TITLE
Question about the model for PPO

### ISSUE THREAD

**Issue by penghao-wu** [metadriverse/ACO#3]
HI, I have several questions about the model used for PPO training.

- Does the model takes navigation command and speed as input the same way as CILRS?
- Do the actor encoder and the critic encoder share the same model?

**Comment by zqh0253** [comment]
Hi, 

> Does the model takes navigation command and speed as input the same way as CILRS?

I modify the model based on DI-drive codebase (not original CILRS), but the overall idea is the same. The speed is used in the encoder to extract feature for actor head and critic head. Navigation command will be used to choose which branch to go through. For example, if we have N commands, then we will instantiate N parallel actor (or critic) heads. If the current command is 0, then we will choose the first actor (or critic) head to predict the action (or value).

> Do the actor encoder and the critic encoder share the same model?

Yes, they share the same model.

**Comment by penghao-wu** [comment]
I think the DI-drive only has a BEV encoder model for PPO training. But it is clear enough now for me to implement it by myself. Thanks a lot.
