### ISSUE TITLE
Which dataset is the provided pre-trained weight trained on?

### ISSUE THREAD

**Issue by yshen47** [metadriverse/ACO#5]
Hello, this is Yuan, who are interested in this great work! I wonder which dataset is the provided pre-trained weight trained on and what the corresponding sampling rate? Thanks!

**Comment by zqh0253** [comment]
Hi Yuan, thanks for the interest!

The pretrained weight is trained on our collected [YouTube Driving Dataset](https://github.com/metadriverse/ACO#dataset). The corresponding sampling rate is 1Hz, which is determined by the `interval` argument [here](https://github.com/metadriverse/ACO/blob/dd992bca2665d11ce76d7b773a31a0d947c28487/code/main_label_moco.py#L275).

**Comment by yshen47** [comment]
Thanks!
