### ISSUE TITLE
Possible for sharing imitation_learning pre-trained weights?

### ISSUE THREAD

**Issue by yshen47** [metadriverse/ACO#6]
Hello ACO team,

This is Yuan from UIUC. I wonder if it is possible to share your imitation learning model and pre-trained weights with me at yshen47@illinois.edu? We hope to use it in our ongoing project if possible. Thanks a lot for your help!

Yuan

**Comment by zqh0253** [comment]
Thanks for your interest!

We released a pretrained ResNet-34, and you can download it [here](https://github.com/metadriverse/ACO#pretrained-weights). As for the imitation learning model, I noticed that you did not specify any training conditions (like how much demonstration data is used). Therefore, I assume you were asking for the general model architecture, which we borrow from [DI-Drive](https://github.com/opendilab/DI-drive/blob/main/core/models/cilrs_model.py).

Qihang
