### ISSUE TITLE
Camera Intrinsic Matrix for the Youtube Driving Videos

### ISSUE THREAD

**Issue by shan18** [metadriverse/ACO#8]
Hi ACO Team,

I wanted to ask that do you guys have the information regarding the camera intrinsic matrix for the videos present in the YouTube driving videos dataset?

Thank you.

**Comment by zqh0253** [comment]
Hi Shantanu,

Thanks for your interest in our project. We do not have the information regarding the camera intrinsic matrix. 

However, you can extract the intrinsic information using some pre-trained networks. FYI, [PPGeo](https://github.com/OpenDriveLab/PPGeo), a follow-up work of ACO, uses a pre-trained [PoseNet](https://github.com/nianticlabs/monodepth2) to estimate the camera information for the videos in the YouTube Driving Dataset. 

Qihang

**Comment by shan18** [comment]
Hi Qihang,

Thanks for the response. I'll go ahead with the PPGeo model to get the intrinsic information.

Thanks,
Shantanu
