### ISSUE TITLE
Unable to extract the dataset on Linux !

### ISSUE THREAD

**Issue by chrissunny94** [metadriverse/ACO#9]
We are able to unzip the ACO dataset on Windows , but unable to extract onLinux .

Can you tell the exact tool / script / plugins that will allow to unpack the files .

**Comment by zqh0253** [comment]
After downloading all the files to local, run:
```
cat sega* > frames.zip
unzip frames.zip
```

**Comment by chrissunny94** [comment]
Ahh thats what it was . Now i got it . Thank you .
